# Generated by Django 2.0 on 2021-10-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auth',
            new_name='author',
        ),
    ]
